### ISSUE TITLE
Add ability to not ignore successive deep links

### ISSUE THREAD

**Issue by seth-gravy** [AppsFlyerSDK/appsflyer-android-sdk#2]
Opening a deep link, backgrounding, then opening up the same deep link results in this log message:

```
I/AppsFlyer_4.9.0: skipping re-use of previously consumed deep link: <redacted> w/sT
```

We'd like to configure the SDK to not ignore these successive links.

**Comment by seth-gravy** [comment]
It looks like the functionality has changed. Now back-to-back identical deep links are no longer ignored; it is now completely time-based. If you open the app with a second deep link within 5 seconds, it is ignored.

```
I/AppsFlyer_4.11.0: Last Launch attempt: 2019/10/29 15:18:33.178 +0000;
    Last successful Launch event: 1969/12/31 23:59:59.999 +0000;
    This launch is blocked: 4259 ms < 5000 ms
```

**Comment by af-vs** [comment]
As of today consecutive deep links should be processed correctly. The minimum time between sessions can also be changed from default 5 seconds using [this API](https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#api-reference-setmintimebetweensessions).

Closing as not relevant anymore, please feel free to reopen if you think otherwise.
Thank you!
