### ISSUE TITLE
What method determines the daily active user statistics

### ISSUE THREAD

**Issue by kartyjoin** [AppsFlyerSDK/appsflyer-android-sdk#27]
AppsFlyerLib.getInstance().init()
or
AppsFlyerLib.getInstance().start() ?

**Comment by ge-af** [comment]
Hi @kartyjoin 

The AppsFlyerLib.getInstance().start() is the method which count DAU since it's the one who creates and count user sessions.

You can think of the init() method as a "warm-up" method which sets up all the configurations of the SDK before it actually invoked anything by the start() one.
