### ISSUE TITLE
subscribeForDeepLink returning wrong DeepLinkResult object

### ISSUE THREAD

**Issue by krobert** [AppsFlyerSDK/appsflyer-android-sdk#30]
Hey,

We are having an issue when using `onelink.me` inside our application.
sdk version: `6.4.3` 

The first deeplink is coming from iterable, which is resolved into a onelink.
After that, since there is no method in the sdk to handle a deeplink programmatically, i navigate the link to an external browser, which opens the app again with the onelink, and calls the right callback:

When i receve the deeplink through `subscribeForDeepLink` callback and trying to access the `deeplinkValue`, i receive a null, because the sdk is parsing it wrong:
```
   appsflyer.subscribeForDeepLink { deepLinkResult ->
            when (deepLinkResult.status) {
                DeepLinkResult.Status.FOUND -> {
                    Timber.d("DeepLink found")
                    val deepLinkObj = deepLinkResult.deepLink
                    var actualDeeplink: String? = ""
                    actualDeeplink = deepLinkObj.deepLinkValue // this returns null
                }
                  ....
            }
            ....
    }
```
See the result i debugged:
![image](https://user-images.githubusercontent.com/6197932/142416798-7c733392-bde1-448b-82b4-9d76a998c579.png)

The value is inside the referrer property, and not as a seperate.

In the website we are not putting anything special, just using this field:
![image](https://user-images.githubusercontent.com/6197932/142416572-31d7b047-764a-4423-8ea6-fc9c2a8b404b.png)

Do you know what we are doing wrong? 
Can you check if this is an issue in appsflyer?

Thanks,
Robert

**Comment by ge-af** [comment]
Hi @krobert 

It looks like we do not allow to add this "/" character inside the `deep_link_value`.
We have an open issue about it internally we is being worked as we speak.

Please see attached image:

![image (9)](https://user-images.githubusercontent.com/87754256/142429916-f53feb1c-b16b-468a-9aab-e8403db3ce80.png)

Please try to use a different deep_link_value and try it again.
If the issue is persistent, we would kindly ask you to submit a support ticket to support@appsflyer.com in order to get optimal support.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
