### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by Damien-L** [AppsFlyerSDK/appsflyer-android-sdk#39]
Hi !

We're facing stacktraces with AppFlyers SDK 6.8.0 :

> Fatal Exception: java.util.NoSuchElementException
>        at java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:2031)
>        at java.util.concurrent.ConcurrentSkipListSet.first(ConcurrentSkipListSet.java:398)
>        at com.appsflyer.internal.bp.AFInAppEventType(:3290)
>        at com.appsflyer.internal.bp$4.run(:133)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>        at java.lang.Thread.run(Thread.java:919)

Do you know this problem ?

**Comment by ge-af** [comment]
Same as in #40.

If needed, please re-open or contact us at support@appsflyer.com in order to get optimal support.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
