### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Damien-L** [AppsFlyerSDK/appsflyer-android-sdk#40]
Hi !

We're facing stacktraces with AppsFlyer 6.8.0.

> Fatal Exception: java.lang.NoSuchMethodError: No static method valueOf(Ljava/lang/String;)Lcom/appsflyer/internal/h; in class Lcom/appsflyer/internal/h; or its super classes (declaration of 'com.appsflyer.internal.h' appears in base.apk)
>        at com.appsflyer.internal.o.AFInAppEventParameterName(o.java:41)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.appsflyer.internal.bb.valueOf(SourceFile:126)
>        at com.appsflyer.internal.bx.values(SourceFile:64)
>        at com.appsflyer.internal.bw.AFInAppEventType(SourceFile:94)
>        at com.appsflyer.internal.bp$4.run(SourceFile:109)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
>        at java.lang.Thread.run(Thread.java:1012)

Do you know this problem ?

**Comment by ge-af** [comment]
Hi @Damien-L 

Thank you for reaching out!

I can see that this stack trace is most likely from v6.7.0 version.
But this crash and also the crash mentioned [here](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/39) (NoSuchElementException) should be fixed in newer SDK versions and are known to us.

We just released version v6.9.0 on Android today, so you can try and integrate with it and check if those occurrences have decreased and/or stopped.

If not, We would kindly ask you to submit a support ticket to support@appsflyer.com in order to get optimal service.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
